### ISSUE TITLE
Pre-filled import TXTs?

### ISSUE THREAD

**Issue by pbuttigieg** [cmungall/ontology-starter-kit#1]
Just curious if the import term TXTs are meant to be pre-populated. Looking at FOODON (cooked up with this kit):
* [CHEBI](https://github.com/FoodOntology/foodon/blob/master/src/ontology/imports/chebi_terms.txt)
* [ENVO](https://github.com/FoodOntology/foodon/blob/master/src/ontology/imports/envo_terms.txt)
* [RO](https://github.com/FoodOntology/foodon/blob/master/src/ontology/imports/ro_terms.txt)

Were these just for seeding?

**Comment by cmungall** [comment]
that may have been an earlier version

Currently a seed file is made for every external ontology specified with `-d`

The contents for each is:

```
http://purl.obolibrary.org/obo/XXX_0000001 ## Optional Label
http://purl.obolibrary.org/obo/BFO_0000050 ## part of
http://purl.obolibrary.org/obo/CHEBI_24431 ## chemical entity
http://purl.obolibrary.org/obo/UBERON_0002048 ## lung
http://purl.obolibrary.org/obo/CL_0000540 ## neuron
http://purl.obolibrary.org/obo/GO_0008150 ## biological_process
```

In theory we could have some smart logic to choose a representative set on a per ontology basis... but not really worth it
