### ISSUE TITLE
Error in running INSTALL.sh - unable to download files

### ISSUE THREAD

**Issue by FrancescoVit** [cmungall/ontology-starter-kit#15]
Hi, very new to this, so bear with me if the issue is trivial.

Running the script INSTALL.sh I keep getting errors "ERROR 504: Gateway Time-out" and "ERROR 502: Bad Gateway" when the script run all the wget commands.

Any troubleshooting?

**Comment by cmungall** [comment]
This is nothing to do with you - there is an upstream issue with the 
server that supplies the software not responding. Should be fixed later 
today.

We should make this part more robust!

**Comment by cmungall** [comment]
please reopen if this continues to be a problem

**Comment by FrancescoVit** [comment]
Forgot to close, it was fixed the day after
