### ISSUE TITLE
"make release" fails

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [cmungall/ontology-starter-kit#17]
The "make release" command didn't work - at least on my brand of make/bash because the code had $RELEASE instead of $(RELEASE) . I think this is fixed as follows:

```
release: $(ONT).owl
# $(ONT).obo # disabled for now
        cp $^ $(RELEASEDIR)/.
        mkdir -p $(RELEASEDIR)/imports/ && cp imports/* $(RELEASEDIR)/imports/
```

**Comment by cmungall** [comment]
huh, odd - I don't see `$RELEASE` here: https://github.com/cmungall/ontology-starter-kit/blob/master/template/src/ontology/Makefile

However, it is possible for problems to occur in owl2obo, particularly if you violate the cardinality expectations of obo format.So commenting out the obo target is fine your community doesn't need it. However, the obo conversion can act as a useful lint check, e.g. to see you don't have >1 text def per term

**Comment by Public-Health-Bioinformatics** [comment]
Ah I just realized this is in the FOODON src/ontology/Makefile , and that's where the obo target was commented out.  So we'll sort this out back there!  Thx.
