### ISSUE TITLE
The -d option does not appear to be optional.

### ISSUE THREAD

**Issue by marijane** [cmungall/ontology-starter-kit#18]
**Steps to reproduce:**
I ran the following command:
`./seed-my-ontology-repo.pl -u openrif -t "Contributor Role Ontology" cro -f`

**Result:**
The script exited with an error.  See attached log file.  Running the script with the -f flag does not work, either.
[seedlog.txt](https://github.com/cmungall/ontology-starter-kit/files/634663/seedlog.txt)

**Expected Result:**
Given that the -d flag is described as an option in the help, I expected it to be optional.

**Comment by cmungall** [comment]
Ah, that's an oversight.

As a workaround try `-d ro` or a small ontology, and then you can simply choose to ignore the dependency stuff ad remove the import

**Comment by cmungall** [comment]
turned out to be an easy fix
