### ISSUE TITLE
Bug: mirror files added to repo

### ISSUE THREAD

**Issue by pbuttigieg** [cmungall/ontology-starter-kit#5]
If we comment out [this](https://github.com/cmungall/ontology-starter-kit/blob/master/seed-my-ontology-repo.pl#L125) git add statement, the mirror files are not added. Seems to be recursive.

from the git  [documentation](https://git-scm.com/docs/git-add)
>
Adds content from all *.txt files under Documentation directory and its subdirectories:
>
$ git add Documentation/\*.txt
>
Note that the asterisk * is quoted from the shell in this example; this **lets the command include the files from subdirectories of Documentation/ directory**.

**Comment by cmungall** [comment]
GitHub seems to be omitting the backslash

But yes, it could be that running this via `runcmd` avoids the shell expansion and instead does it in git
